/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dragolon28.soundboard;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.formdev.flatlaf.FlatDarkLaf;
import java.io.*;
import java.util.*;
import javafx.application.Platform;
import javax.swing.*;

/**
 *
 * @author zack
 */
public class SoundBoardUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SoundBoardUI.class.getName());
    private static String filepath;
    private static ArrayList<File> soundArray = new ArrayList<>();
    private static SoundEffectButton[] buttons;
    private static Scanner config;
    private static PrintStream configOut;
    private static File configFile;
    private static ObjectMapper mapper;
    private static String jsonName;
    private static boolean muted;
    public static int volume;
    /**
     * Creates new form SounBoardUI
     * @throws java.io.IOException
     */
    public SoundBoardUI() throws IOException{
        initComponents();
        Platform.startup(() -> {});
        configFile = new File("SoundBoardConfig.txt");
        if (!configFile.exists()){
            configFile.createNewFile();
        }
        config = new Scanner(configFile);
        if (config.hasNext()){
            filepath = config.nextLine();
        } else {filepath = "";}
        if (config.hasNextInt()){
            volume = config.nextInt();
        } else{volume = 100;}
        masterVolume.setValue(volume);
        logToApp("Path: " + filepath);
        config.close();
        
        try {
            makeSoundArray(filepath);
            makeButtons();
            logToApp("Made Buttons");
        }
        catch(Exception e){
            System.getLogger(SoundBoardUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, e);
        }
        String[] pathWords = filepath.split("/");
        jsonName = pathWords[pathWords.length-1];
        if (new File(filepath).listFiles() != null)
            jsonName +=(new File(filepath).listFiles().length);
        try{readJson();} catch(Exception e){}
        muted = false;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        soundFolderSelector = new javax.swing.JFileChooser();
        helpPane = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        folderChoose = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        muteButton = new javax.swing.JToggleButton();
        masterVolume = new javax.swing.JSlider();
        volumeLabel = new javax.swing.JLabel();

        soundFolderSelector.setAcceptAllFileFilterUsed(false);
        soundFolderSelector.setCurrentDirectory(new java.io.File("/Users/zack/Documents/Python/Theatre Soundborad"));
        soundFolderSelector.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        helpPane.setMessage("The \'Folder\' button allows you to choose a folder to pull sounds from.\nThe \'Save Json\' button saves current configuration.\nThe \'Load Json\' button loads the last known configuration for this folder.\n\nThe top button of the sounds tiles plays the sound.\nThe bar below that shows the current position of playback.\nThe slider below that sets a start offset.\nThe slider below that changes the playback volume of a sound.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Theater SoundBoard");
        setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        setPreferredSize(new java.awt.Dimension(2000, 1500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new java.awt.GridLayout(0, 4));
        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 234;
        gridBagConstraints.ipady = 294;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        folderChoose.setText("Folder");
        folderChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderChooseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(folderChoose, gridBagConstraints);

        saveButton.setText("Save Json");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(saveButton, gridBagConstraints);

        loadButton.setText("Load Json");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(loadButton, gridBagConstraints);

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(helpButton, gridBagConstraints);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(1);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(10);
        jTextArea1.setTabSize(1);
        jTextArea1.setWrapStyleWord(true);
        jPanel2.add(jTextArea1, java.awt.BorderLayout.SOUTH);

        jScrollPane3.setViewportView(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        muteButton.setText("Mute");
        muteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(muteButton, gridBagConstraints);

        masterVolume.setMajorTickSpacing(25);
        masterVolume.setOrientation(javax.swing.JSlider.VERTICAL);
        masterVolume.setPaintLabels(true);
        masterVolume.setPaintTicks(true);
        masterVolume.setMinimumSize(new java.awt.Dimension(51, 200));
        masterVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                masterVolumeStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(masterVolume, gridBagConstraints);

        volumeLabel.setText("Volume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(volumeLabel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            makeJson(jsonName);
        } catch (IOException ex) {}
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        try {
            readJson();
        } catch (IOException ex) {
            System.getLogger(SoundBoardUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void folderChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderChooseActionPerformed
        if (soundFolderSelector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
             makeSoundArray(soundFolderSelector.getSelectedFile().getAbsolutePath());
             filepath = soundFolderSelector.getSelectedFile().getAbsolutePath();
             logToApp("Path: " + filepath);
             makeButtons();
             try {
                 writeConfig();
             } catch (IOException ex) {
                 System.getLogger(SoundBoardUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
             updateJsonName();
             
         }
    }//GEN-LAST:event_folderChooseActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        helpPane.showMessageDialog(this, "The \'Folder\' button allows you to choose a folder to pull sounds from.\nThe \'Save Json\' button saves current configuration.\nThe \'Load Json\' button loads the last known configuration for this folder.\n\nThe top button of the sounds tiles plays the sound.\nThe bar below that shows the current position of playback.\nThe slider below that sets a start offset.\nThe slider below that changes the playback volume of a sound.", "Help", -1);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void muteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteButtonActionPerformed
        if(muted == true){
            volume = masterVolume.getValue();
            muted = false;
            for (SoundEffectButton button :buttons){
                button.muted(false);
            }
            logToApp("Unmuted");
        }
        else{volume = 0;
            muted = true;
            for (SoundEffectButton button :buttons){
                button.muted(true);
            }
            logToApp("Muted");
        }
    }//GEN-LAST:event_muteButtonActionPerformed

    private void masterVolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_masterVolumeStateChanged
        volume = masterVolume.getValue();
        try {
            writeConfig();
        } catch (IOException ex) {
            System.getLogger(SoundBoardUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_masterVolumeStateChanged
    
    private void writeConfig() throws IOException{
        configOut = new PrintStream(configFile);
        configOut.println(filepath);
        configOut.println(volume);
        configOut.close();
    }
    
    private void makeSoundArray(String path){
        soundArray = new ArrayList<>();
        for (File f : new File(path).listFiles()){
            if (f.getName().contains(".wav") || f.getName().contains(".mp3")){
                soundArray.add(f);
            }
        }
    }
    
    public void logToApp(String msg){
        String console = jTextArea1.getText();
        console += "\n>"+msg;
        jTextArea1.setText(console);
    }
    
    private void makeJson(String filename) throws IOException{
        updateJsonName();
        
        mapper = new ObjectMapper();
        mapper.enable(SerializationFeature.INDENT_OUTPUT);
        
        File testJson;
        
        try {
            logToApp("Saving JSON");
            testJson = new File("jsonConfigs/" + filename + ".json");
            if (!testJson.exists())
                throw new Exception();
        } catch(Exception e){
            logToApp("Failed to grab file");
            try{
                logToApp("Tried to make file");
            PrintStream jsonMaker = new PrintStream("jsonConfigs/" + filename + ".json");
            jsonMaker.print("");
            jsonMaker.close();
            } catch(Exception ex){
                logToApp("Failed, making folder");
                new File("jsonConfigs").mkdir();
                PrintStream jsonMaker = new PrintStream("jsonConfigs/" + filename + ".json");
                jsonMaker.print("");
                jsonMaker.close();
            }
            testJson = new File("jsonConfigs/" + filename + ".json");
        }
        
        JsonGenerator g = mapper.createGenerator(testJson, JsonEncoding.UTF8);
        g.writeStartObject();
        g.writeStringField("path", filepath);
        for (SoundEffectButton button : buttons){
            g.writeArrayFieldStart(button.getPath());
            g.writeArray(button.getValues(), 0, 2);
            g.writeEndArray();
        }
        g.writeEndObject();
        g.close();
    }
    
    private void readJson() throws IOException{
        updateJsonName();
        try {
            String path = "jsonConfigs/"+jsonName+".json";
            mapper = new ObjectMapper();
            logToApp("Reading JSON: " + jsonName);
            JsonNode tree = mapper.readTree(new File(path));
            for (SoundEffectButton button: buttons){
                button.setVolume(tree.get(button.getPath()).get(0).get(1).asInt());
                button.setStartPos(tree.get(button.getPath()).get(0).get(0).asInt());
            }
            jPanel1.validate();
            jPanel1.repaint();
        } catch (Exception ex) {
            logToApp("No appropriate JSON found, skipping");
        }
        
    }
    
    private void updateJsonName(){
        String[] pathWords = filepath.split("/");
        jsonName = pathWords[pathWords.length-1];
        jsonName +=(new File(filepath).listFiles().length);
    }
    
    private void makeButtons(){
        jPanel1.removeAll();
        buttons = new SoundEffectButton[soundArray.size()];
        for (int i = 0; i < buttons.length; i++){
            if (soundArray.get(i).getName().contains(".mp3") || soundArray.get(i).getName().contains(".wav")){
                try {
                    buttons[i] = new SoundEffectButton(soundArray.get(i), this);
                } catch (IOException ex) {
                    System.getLogger(SoundBoardUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                jPanel1.add(buttons[i]);
            }
        }
        jPanel1.validate();
        jPanel1.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        FlatDarkLaf.setup();
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new SoundBoardUI().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(SoundBoardUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton folderChoose;
    private javax.swing.JButton helpButton;
    private javax.swing.JOptionPane helpPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadButton;
    private javax.swing.JSlider masterVolume;
    private javax.swing.JToggleButton muteButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JFileChooser soundFolderSelector;
    private javax.swing.JLabel volumeLabel;
    // End of variables declaration//GEN-END:variables
}
