/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dragolon28.soundboard;
import java.awt.event.ActionEvent;
import java.io.*;
import javafx.scene.media.*;
import javafx.util.Duration;
import javax.swing.Timer;
/**
 *
 * @author zack
 */
public class SoundEffectButton extends javax.swing.JPanel implements java.awt.event.ActionListener{

    private final File file;
    private MediaPlayer sound;
    private Duration time;
    private Timer timer;
    private SoundBoardUI container;

    /**
     * Creates new form SoundEffectButton
     * @param file
     * @param container
     * @throws java.io.IOException
     */
    public SoundEffectButton(File file, SoundBoardUI container) throws IOException {
        initComponents();
        this.file = file;
        this.container = container;
        
        soundName.setText(file.getName());
        startPosLabel.setText(startPosSlider.getValue()*0.25+"s");
        volumeLabel.setText(volumeSlider.getValue()+"%");
        sound = new MediaPlayer(new Media(file.toURI().toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        playButton = new javax.swing.JButton();
        startPosLabel = new javax.swing.JLabel();
        playPos = new javax.swing.JProgressBar();
        volumeLabel = new javax.swing.JLabel();
        startPosSlider = new javax.swing.JSlider();
        volumeSlider = new javax.swing.JSlider();
        soundName = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(250, 211));
        setPreferredSize(new java.awt.Dimension(250, 211));
        setLayout(new java.awt.GridBagLayout());

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(playButton, gridBagConstraints);

        startPosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startPosLabel.setText("startpos");
        startPosLabel.setToolTipText("The start position offset of the sound effect.");
        startPosLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startPosLabel.setMaximumSize(new java.awt.Dimension(64, 20));
        startPosLabel.setMinimumSize(new java.awt.Dimension(64, 20));
        startPosLabel.setPreferredSize(new java.awt.Dimension(64, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(startPosLabel, gridBagConstraints);

        playPos.setValue(100);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(playPos, gridBagConstraints);

        volumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel.setText("volume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(volumeLabel, gridBagConstraints);

        startPosSlider.setMajorTickSpacing(2);
        startPosSlider.setMaximum(8);
        startPosSlider.setMinorTickSpacing(1);
        startPosSlider.setPaintTicks(true);
        startPosSlider.setSnapToTicks(true);
        startPosSlider.setToolTipText("Start Position");
        startPosSlider.setValue(0);
        startPosSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                startPosSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        add(startPosSlider, gridBagConstraints);

        volumeSlider.setSnapToTicks(true);
        volumeSlider.setToolTipText("");
        volumeSlider.setValue(100);
        volumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        add(volumeSlider, gridBagConstraints);

        soundName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        soundName.setText("soundName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(9, 5, 9, 5);
        add(soundName, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == timer){
            if (sound.getCurrentTime().equals(time)){
                timer.stop();
                playPos.setValue(100);
            }
            else{
                playPos.setValue((int) ((sound.getCurrentTime().toMillis()/time.toMillis())*100));
            }
        }
    }
    
    
    private void playSound() {
        container.logToApp("Playing sound: " + file.getName());
        sound.setVolume(((double)volumeSlider.getValue())/100);
        System.out.println(((double)volumeSlider.getValue())/100);
        sound.seek(Duration.seconds(((double)startPosSlider.getValue())*0.25));
        
        sound.play();
        time = sound.getTotalDuration();
        updatePosBar();
    }
    
    private void updatePosBar(){
        timer = new Timer(20, this);
        timer.start();
    }
    
    private void startPosSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_startPosSliderStateChanged
        startPosLabel.setText(startPosSlider.getValue()*0.25+"s");
    }//GEN-LAST:event_startPosSliderStateChanged

    private void volumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
        volumeLabel.setText(volumeSlider.getValue()+"%");
    }//GEN-LAST:event_volumeSliderStateChanged

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        playSound();
    }//GEN-LAST:event_playButtonActionPerformed

    public int[] getValues(){
        return new int[]{startPosSlider.getValue(), volumeSlider.getValue()};
    }
    
    public String getPath(){
        return file.getAbsolutePath();
    }
    
    public void setStartPos(int pos){
        startPosSlider.setValue(pos);
    }
    
    public void setVolume(int volume){
        volumeSlider.setValue(volume);
    }
    
    @Override
    public String toString(){
        return file.getName();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton playButton;
    private javax.swing.JProgressBar playPos;
    private javax.swing.JLabel soundName;
    private javax.swing.JLabel startPosLabel;
    private javax.swing.JSlider startPosSlider;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables

}
